root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/publisher ."
  bin = "tmp/main"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
